targets:
  OBAKit:
    type: framework
    platform: iOS
    sources: ["."]
    dependencies:
      - target: OBAKitCore
      - package: BLTNBoard
      - package: Hyperconnectivity
      - package: Eureka
      - package: FloatingPanel
      - package: MarqueeLabel
      - package: OTPKit
    postBuildScripts:
      - path: "../scripts/swiftlint.sh"
        name: Swiftlint
        basedOnDependencyAnalysis: false
    scheme:
      gatherCoverageData: true
    info:
      path: "Info.plist"
      properties:
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
    settings:
      base:
        APPLICATION_EXTENSION_API_ONLY: false
      configs:
          Debug:
            LD_RUNPATH_SEARCH_PATHS:
              - "$(inherited)"
              - "@executable_path/Frameworks"
          Release:
            LD_RUNPATH_SEARCH_PATHS:
              - "$(inherited)"
              - "@executable_path/Frameworks"
