targets:
  OBAWidget:
    type: app-extension
    supportedDestinations: [iOS]
    sources: ["."]
    dependencies:
      - target: OBAKitCore
      - sdk: SwiftUI.framework
      - sdk: WidgetKit.framework
    entitlements:
      path: OBAWidget.entitlements
    info:
      path: Info.plist
      properties:
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension
    settings:
      base:
        APPLICATION_EXTENSION_API_ONLY: true

