############
# OneBusAway
############

options:
  bundleIdPrefix: org.onebusaway

targets:
  App:
    sources:
      - path: Apps/OneBusAway
        name: App
        group: OneBusAway
      - path: Apps/Shared/Analytics
        name: Analytics
        group: OneBusAway
      - path: Apps/Shared/CommonClient
        name: Common
        group: OneBusAway
      - path: Apps/Shared/OneSignal
        name: OneSignal
        group: OneBusAway
    dependencies:
      - package: OneSignal
    entitlements:
      path: Apps/OneBusAway/OneBusAway.entitlements
      properties:
        com.apple.security.application-groups:
          - group.org.onebusaway.iphone
        com.apple.developer.associated-domains:
          - applinks:onebusaway.co
          - applinks:www.onebusaway.co
          - applinks:alerts.onebusaway.org
    info:
      path: Apps/OneBusAway/Info.plist
      properties:
        CFBundleDisplayName: OneBusAway
        CFBundleURLTypes: [{CFBundleTypeRole: "Editor", CFBundleURLIconFile: "", CFBundleURLName: "onebusaway", CFBundleURLSchemes: ["onebusaway"]}]
        LSApplicationQueriesSchemes:
          - fb
          - twitter
          - comgooglemaps
          - fb313213768708402HART
          - org.sdmts.riderapp.compassmobile.payments
          - org.sdmts.pronto
          - co.bytemark.tgt
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: false
          NSExceptionDomains: {
            "onebusaway.co": {
                NSIncludesSubdomains: true,
                NSExceptionAllowsInsecureHTTPLoads: true
            }
          }
        NSHumanReadableCopyright: © Open Transit Software Foundation
        NSUserActivityTypes:
          - org.onebusaway.iphone.user_activity.stop
          - org.onebusaway.iphone.user_activity.trip
        OBAKitConfig:
          AppDevelopersEmailAddress: iphone-app@onebusaway.org
          AppGroup: group.org.onebusaway.iphone
          BundledRegionsFileName: regions.json
          DeepLinkServerBaseAddress: https://onebusaway.co
          ExtensionURLScheme: onebusaway
          PrivacyPolicyURL: https://onebusaway.org/privacy/
          PushNotificationAPIKey: d5d0d28a-6091-46cd-9627-0ce01ffa9f9e
          RESTServerAPIKey: org.onebusaway.iphone
          RegionsServerBaseAddress: https://regions.onebusaway.org
          RegionsServerAPIPath: /regions-v3.json
    settings:
      base:
        DEVELOPMENT_TEAM: 4ZQCMA634J
        PRODUCT_BUNDLE_IDENTIFIER: org.onebusaway.iphone
  TodayView:
    sources: ["Apps/OneBusAway/Assets.xcassets"]
    entitlements:
      properties:
        com.apple.security.application-groups:
          - group.org.onebusaway.iphone
    info:
      properties:
        CFBundleDisplayName: OneBusAway
        OBAKitConfig:
          AppGroup: group.org.onebusaway.iphone
          BundledRegionsFileName: regions.json
          DeepLinkServerBaseAddress: https://onebusaway.co
          ExtensionURLScheme: onebusaway
          RESTServerAPIKey: org.onebusaway.iphone
          RegionsServerBaseAddress: https://regions.onebusaway.org
          RegionsServerAPIPath: /regions-v3.json
    settings:
      base:
        DEVELOPMENT_TEAM: 4ZQCMA634J
        PRODUCT_BUNDLE_IDENTIFIER: org.onebusaway.iphone.TodayView

include:
  - path: Apps/Shared/app_shared.yml
  - path: Apps/Shared/analytics_fx_config.yml
  - path: Apps/Shared/push_config.yml
  - path: OBAKitCore/project.yml
  - path: OBAKitCoreTests/project.yml
  - path: OBAKit/project.yml
  - path: OBAKitTests/project.yml
  - path: OBAKitUITests/project.yml
  - path: TodayView/project.yml
