############
# KiedyBus
############

options:
  bundleIdPrefix: pl.kiedybus

targets:
  App:
    sources:
      - path: Apps/KiedyBus
        name: App
        group: KiedyBus
      - path: Apps/Shared/CommonClient
        name: Common
        group: KiedyBus
    entitlements:
      path: Apps/KiedyBus/KiedyBus.entitlements
      properties:
        com.apple.security.application-groups:
          - group.pl.kiedybus.iphone
    info:
      path: Apps/KiedyBus/Info.plist
      properties:
        CFBundleDisplayName: KiedyBus
        CFBundleURLTypes: [{CFBundleTypeRole: "Editor", CFBundleURLIconFile: "", CFBundleURLName: "kiedybus", CFBundleURLSchemes: ["kiedybus"]}]
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: false
          NSExceptionDomains:
            goeuropa.eu:
              NSTemporaryExceptionAllowsInsecureHTTPLoads: true
              NSIncludesSubdomains: true
            iplaner.pl:
              NSTemporaryExceptionAllowsInsecureHTTPLoads: true
              NSIncludesSubdomains: true
            kiedybus.pl:
              NSTemporaryExceptionAllowsInsecureHTTPLoads: true
              NSIncludesSubdomains: true
        NSHumanReadableCopyright: © goEuropa
        NSLocationAlwaysAndWhenInUseUsageDescription: Show your location on the map
        NSLocationWhenInUseUsageDescription: Show your location on the map
        NSUserActivityTypes:
          - pl.kiedybus.iphone.user_activity.stop
          - pl.kiedybus.iphone.user_activity.trip
        OBAKitConfig:
          AppDevelopersEmailAddress: info@goeuropa.eu
          AppGroup: group.pl.kiedybus.iphone
          BundledRegionsFileName: regions.json
          ExtensionURLScheme: kiedybus
          PrivacyPolicyURL: https://www.goeuropa.eu
          RESTServerAPIKey: web
          RegionsServerBaseAddress: http://kiedybus.pl
          RegionsServerAPIPath: /regions-v4.json
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: pl.kiedybus.iphone
  TodayView:
    sources: ["Apps/KiedyBus/Assets.xcassets"]
    entitlements:
      properties:
        com.apple.security.application-groups:
          - group.pl.kiedybus.iphone
    info:
      properties:
        CFBundleDisplayName: KiedyBus
        OBAKitConfig:
          AppGroup: group.pl.kiedybus.iphone
          BundledRegionsFileName: regions.json
          ExtensionURLScheme: kiedybus
          RESTServerAPIKey: web
          RegionsServerBaseAddress: https://kiedybus.pl
          RegionsServerAPIPath: /regions-v4.json
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: pl.kiedybus.iphone.TodayView

include:
  - path: Apps/Shared/app_shared.yml
  - path: OBAKitCore/project.yml
  - path: OBAKitCoreTests/project.yml
  - path: OBAKit/project.yml
  - path: OBAKitTests/project.yml
  - path: OBAKitUITests/project.yml
  - path: TodayView/project.yml
