targets:
  OBAKitTests:
    type: bundle.unit-test
    platform: iOS
    sources: ["."]
    dependencies:
      - target: App
      - package: Nimble
    info:
      path: "Info.plist"
      properties:
        NSPrincipalClass: OBAKitTests.OBAKitTestsSetup
packages:
  Nimble:
    url: https://github.com/Quick/Nimble.git
    from: 13.7.0
