//
//  TransitArrivalAttributes.swift
//  OBAKitCore
//
//  Copyright © Open Transit Software Foundation
//  This source code is licensed under the Apache 2.0 license found in the
//  LICENSE file in the root directory of this source tree.
//

import ActivityKit
import Foundation
import CoreLocation

/// ActivityKit attributes for tracking a transit arrival/departure as a Live Activity.
///
/// Static data is set once when the activity starts; `ContentState` is updated
/// as new arrival data arrives from the API.
@available(iOS 16.2, *)
public struct TransitArrivalAttributes: ActivityAttributes {

    // MARK: - Static (set once at start)

    /// Human-readable stop name, e.g. "E Pine St & 15th Ave"
    public let stopName: String

    /// Route short name, e.g. "49"
    public let routeShortName: String

    /// Trip headsign, e.g. "University District"
    public let tripHeadsign: String

    /// Stop ID used to deep-link back to the stop page.
    public let stopID: StopID

    /// Region identifier used alongside stopID for deep-linking.
    public let regionIdentifier: Int

    /// Stop coordinate — used to render the map snapshot in the Dynamic Island.
    public let stopLatitude: Double
    public let stopLongitude: Double

    public init(stopName: String, routeShortName: String, tripHeadsign: String, stopID: StopID, regionIdentifier: Int, stopLatitude: Double = 0, stopLongitude: Double = 0) {
        self.stopName = stopName
        self.routeShortName = routeShortName
        self.tripHeadsign = tripHeadsign
        self.stopID = stopID
        self.regionIdentifier = regionIdentifier
        self.stopLatitude = stopLatitude
        self.stopLongitude = stopLongitude
    }

    // MARK: - Dynamic (updated as data refreshes)

    public struct ContentState: Codable, Hashable {

        /// The best available arrival/departure time (predicted if available, otherwise scheduled).
        public let arrivalDepartureDate: Date

        /// Minutes until arrival/departure. Negative = already passed.
        public let minutesUntilArrival: Int

        /// Whether this time is based on real-time prediction.
        public let isPredicted: Bool

        /// Schedule status: early, onTime, delayed.
        public let scheduleStatus: ScheduleStatusState

        /// PNG-encoded Apple Maps snapshot centered on the stop.
        /// Generated by MKMapSnapshotter on the app side; displayed as a static Image in the widget.
        public let mapImageData: Data?

        public init(
            arrivalDepartureDate: Date,
            minutesUntilArrival: Int,
            isPredicted: Bool,
            scheduleStatus: ScheduleStatusState,
            mapImageData: Data? = nil
        ) {
            self.arrivalDepartureDate = arrivalDepartureDate
            self.minutesUntilArrival = minutesUntilArrival
            self.isPredicted = isPredicted
            self.scheduleStatus = scheduleStatus
            self.mapImageData = mapImageData
        }

        /// Convenience init from an `ArrivalDeparture`.
        public init(arrivalDeparture: ArrivalDeparture, mapImageData: Data? = nil) {
            self.arrivalDepartureDate = arrivalDeparture.arrivalDepartureDate
            self.minutesUntilArrival = arrivalDeparture.arrivalDepartureMinutes
            self.isPredicted = arrivalDeparture.predicted
            self.scheduleStatus = ScheduleStatusState(from: arrivalDeparture.scheduleStatus)
            self.mapImageData = mapImageData
        }
    }
}

// MARK: - ScheduleStatusState

/// A Codable mirror of `OBAKitCore.ScheduleStatus` for use in ActivityKit ContentState.
public enum ScheduleStatusState: String, Codable, Hashable {
    case early, onTime, delayed, unknown

    @available(iOS 16.2, *)
    public init(from status: ScheduleStatus) {
        switch status {
        case .early:   self = .early
        case .onTime:  self = .onTime
        case .delayed: self = .delayed
        default:       self = .unknown
        }
    }
}
