############
# OneBusAway
############

options:
  bundleIdPrefix: info.mta

targets:
  App:
    sources:
      - path: Apps/MTA
        name: App
        group: MTA
      - path: Apps/Shared/CommonClient
        name: Common
        group: MTA
    entitlements:
      path: Apps/MTA/MTA.entitlements
      properties:
        com.apple.security.application-groups:
          - group.info.mta.bustime
        com.apple.developer.associated-domains:
          - applinks:onebusaway.co
          - applinks:www.onebusaway.co
          - applinks:alerts.onebusaway.org
    info:
      path: Apps/MTA/Info.plist
      properties:
        CFBundleDisplayName: MTA Bus Time
        CFBundleURLTypes: [{CFBundleTypeRole: "Editor", CFBundleURLIconFile: "", CFBundleURLName: "onebusaway", CFBundleURLSchemes: ["onebusaway"]}]
        LSApplicationQueriesSchemes:
          - fb
          - twitter
          - comgooglemaps
          - fb313213768708402HART
          - org.sdmts.riderapp.compassmobile.payments
          - org.sdmts.pronto
          - co.bytemark.tgt
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: false
          NSExceptionDomains: {
            "onebusaway.co": {
                NSIncludesSubdomains: true,
                NSExceptionAllowsInsecureHTTPLoads: true
            }
          }
        NSHumanReadableCopyright: © Metropolitan Transportation Authority
        NSUserActivityTypes:
          - info.mta.bustime.user_activity.stop
          - info.mta.bustime.user_activity.trip
        OBAKitConfig:
          AppDevelopersEmailAddress: iphone-app@onebusaway.org
          AppGroup: group.info.mta.bustime
          BundledRegionsFileName: regions.json
          ExtensionURLScheme: bustime
          PrivacyPolicyURL: https://new.mta.info/privacy-policy
          PushNotificationAPIKey: d5d0d28a-6091-46cd-9627-0ce01ffa9f9e
          RESTServerAPIKey: test
          RegionsServerBaseAddress: https://regions.onebusaway.org
          RegionsServerAPIPath: /regions-v3.json
    settings:
      base:
        DEVELOPMENT_TEAM: 4ZQCMA634J
        PRODUCT_BUNDLE_IDENTIFIER: info.mta.bustime
  TodayView:
    sources: ["Apps/MTA/Assets.xcassets"]
    entitlements:
      properties:
        com.apple.security.application-groups:
          - group.info.mta.bustime
    info:
      properties:
        CFBundleDisplayName: MTA Bus Time
        OBAKitConfig:
          AppGroup: group.info.mta.bustime
          BundledRegionsFileName: regions.json
          ExtensionURLScheme: bustime
          RESTServerAPIKey: test
          RegionsServerBaseAddress: https://regions.onebusaway.org
          RegionsServerAPIPath: /regions-v3.json
    settings:
      base:
        DEVELOPMENT_TEAM: 4ZQCMA634J
        PRODUCT_BUNDLE_IDENTIFIER: info.mta.bustime.TodayView

include:
  - path: Apps/Shared/app_shared.yml
  - path: OBAKitCore/project.yml
  - path: OBAKit/project.yml
  - path: OBAKitTests/project.yml
  - path: OBAKitUITests/project.yml
  - path: TodayView/project.yml
