#!/usr/bin/env ruby

app = ARGV[0]

if app.nil?
  display_usage_information
  puts ""
  puts "Defaulting to OneBusAway."
  app = "OneBusAway"
  puts ""
end

check_for_project_file(app)

generate_project(app)

puts `scripts/version`

BEGIN {
  def display_usage_information
    puts "Usage: scripts/generate_project <APP NAME>"
    puts "Available Apps:"
    apps = (Dir.glob("Apps/*") - ["Apps/Shared"]).sort
    apps.each do |app|
      puts "  #{app.split("/").last}"
    end
  end

  def check_for_project_file(app)
    path = project_yml_path(app)
    if !File.exist?(path)
      puts "#{path} does not exist! Create the file and try again!"
      exit
    end
  end

  def generate_project(app)
    `rm -rf OBAKit.xcodeproj`
    `cp #{project_yml_path(app)} .`
    puts `xcodegen`
    `mkdir -p OBAKit.xcodeproj/project.xcworkspace/xcshareddata/swiftpm`
    `cp #{package_resolved_path(app)} OBAKit.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/`
  end

  def project_yml_path(app)
    "Apps/#{app}/project.yml"
  end

  def package_resolved_path(app)
    "Apps/#{app}/Package.resolved"
  end
}