targets:
  OBAKitCore:
    type: framework
    platform: [iOS, watchOS]
    deploymentTarget:
      watchOS: "11.0"
    sources: ["."]
    dependencies:
      - package: SwiftProtobuf
    scheme:
      gatherCoverageData: true
    info:
      path: "Info.plist"
      properties:
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
    settings:
      base:
        APPLICATION_EXTENSION_API_ONLY: true
        BUILD_LIBRARY_FOR_DISTRIBUTION: YES