targets:
  OBAKitCore:
    type: framework
    supportedDestinations: [iOS, watchOS]
    deploymentTarget:
      iOS: "17.0"
      watchOS: "10.0"
    sources: ["."]
    dependencies:
      - package: SwiftProtobuf
    scheme:
      gatherCoverageData: true
    info:
      path: "Info.plist"
      properties:
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
    settings:
      base:
        APPLICATION_EXTENSION_API_ONLY: true
