targets:
  OBAKitCore:
    type: framework
    platform: iOS
    sources: ["."]
    dependencies:
      - package: CocoaLumberjack
      - package: CocoaLumberjackSwift
      - package: MetaCodable
      - package: SwiftProtobuf
      - package: GRDB
    scheme:
      gatherCoverageData: true
    info:
      path: "Info.plist"
      properties:
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
    settings:
      base:
        APPLICATION_EXTENSION_API_ONLY: true
