targets:
  OBAWatchApp:
    type: application
    platform: watchOS
    sources: 
      - path: .
    entitlements:
      path: OBA Watch App.entitlements
      properties:
        com.apple.security.application-groups:
          - group.org.onebusaway.iphone
    info:
      path: OBAWatch-AppInfo.plist
      properties:
        CFBundleDisplayName: OneBusAway
        WKApplication: true
        WKCompanionAppBundleIdentifier: org.onebusaway.iphone
        OBAKitConfig:
          AppGroup: group.org.onebusaway.iphone
          RESTServerAPIKey: org.onebusaway.iphone
    settings:
      base:
        CODE_SIGN_ALLOW_ENTITLEMENTS_MODIFICATION: "YES"
        PRODUCT_BUNDLE_IDENTIFIER: org.onebusaway.iphone.watchkitapp
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        I_PHONE_OS_DEPLOYMENT_TARGET: "18.0"
        WATCHOS_DEPLOYMENT_TARGET: "11.0"
        INFOPLIST_KEY_WKCompanionAppBundleIdentifier: org.onebusaway.iphone
    dependencies:
      - target: OBAKitCore
